[tool.poetry]
name = "headermapper"
version = "0.1.0"
description = "HeaderMapper implemented in Python"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "**/*.py", from = "."}]

[tool.poetry.dependencies]
python = "^3.9"
openpyxl = ">=3.1.2"
fuzzywuzzy = ">=0.18.0"
python-Levenshtein = ">=0.21.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
